### PR TITLE
Make whole workshop citable (fix #3)

### LINKED ISSUE #3: Archive on Zenodo
- [-] check compatibility with ["gemeinsames Webportal"](http://www.wissenschaft-im-digitalen-wandel.de/wissdw/DE/Home/ideenwettbewerb.pdf?__blob=publicationFile)
- [x] remove all info that was only relevant before
- [-] decide from which account (TIB-ORCID available by then?)
- [x] Files from Google Drive: ~~live versions or~~ PDFs?
- [-] go through https://zenodo.org/account/settings/github/

### PR DESCRIPTION
**Pull request by katrinleinweber**
Hi @konrad @lwjohnst86 @mkuzak @mrtnhmtz! Are you OK with [all your names in the citation](https://github.com/TIBHannover/2018-07-09-FAIR-Data-and-Software/pull/15/files#diff-4d7570ca7e02ca3e76695d11e121a8a0) of the whole workshop and its PDFs?

Compared to the versions we presented, I added the video-DOIs to the title slides.

If yes, the plan after merging is as follows:

- [x] check #3 first
- ~~set up sync with Zenodo~~
- ~~release v0.9-beta~~
- ~~add DOI & final links here~~
- ~~release v1.0~~
- [x] Alternative: archive PDFs manually, relate video-DOIs & add DOI badge to website
- [x] remove PDFs from here & merge only the `CITATION` file
- [-] add note about Zenodo-URL to https://tib.eu/cloud/s/tXSt3j7Bg3ySdXY

### CODE REVIEW

**Comment by ghost** [comment]
Looks fine to me. Thank's a lot for taking care. In case you may add the affiliation as well then use "Helmholtz Centre Potsdam - GFZ German Research Centre for Geosciences" for me please.

**Review by lwjohnst86 — APPROVED** [review]
Fine by me! Thanks :)

**Comment by konrad** [comment]
Thanks @katrinleinweber. Looks good. I just added the abbreviation for my second name.

**Comment by mkuzak** [comment]
Thank you, Katrin. Looks good.

**Pull request merged**
